get:
  tags:
    - "TagConfigurations"
  operationId: "getTagConfigurations"
  description: "Gets all tag configurations that are applicable to the provided task"
  parameters:
    - name: "task"
      in: "query"
      description: "The id of the task to get applicable tag configurations for"
      required: true
      schema:
        type: "string"
    - name: "includeHidden"
      in: "query"
      description: "Include tags that are normally hidden and automatically added when registering time on the task"
      required: false
      schema:
        type: "boolean"
  responses:
    "200":
      description: "List of valid tag configurations for the requested task"
      content:
        application/json:
          schema:
            $ref: "./schemas/TagConfigurationResponse.yaml"
    "401":
      $ref: "./responses/UnauthorizedError.yaml"
    "404":
      description: "Unable to find tag configurations for the specified task (Task does not exist)"