openapi: "3.0.3"
info:
  title: "TriReg2 API"
  description: "An OpenAPI specification for time registrations"
  version: "0.0.7"
servers:
- url: "http://0.0.0.0:8080"
paths:
  /login:
    $ref: login.yaml
  /time-registration:
    $ref: time-registration.yaml
  /export:
    $ref: export.yaml
  /tag:
    $ref: tagging.yaml
  /import:
    $ref: import.yaml
  /task:
    $ref: tasks.yaml
  /config/tag:
    $ref: tagConfiguration.yaml
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://oidc.hosted.trifork.com/auth/realms/trifork/.well-known/openid-configuration
    basicAuth:
      type: http
      scheme: basic
  schemas:
    TimeRegistrationRequest:
      $ref: "./schemas/TimeRegistrationRequest.yaml"
    TimeRegistrationResponse:
      $ref: "./schemas/TimeRegistrationResponse.yaml"
security:
- openId:
  - openid
- basicAuth: []
