openapi: "3.0.3"
info:
  title: "Trireg2 API"
  description: "A JSON API for time registration"
  version: "0.0.3"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /time-registration/:
    $ref: time-registration.yaml
  /export/:
    $ref: export.yaml
  /tag/:
    $ref: tagging.yaml
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: /openid-configuration # TODO placeholder until we get real URL
  schemas:
    TimeRegistrationRequest:
      $ref: "./schemas/TimeRegistrationRequest.yaml"
    TimeRegistrationResponse:
      $ref: "./schemas/TimeRegistrationResponse.yaml"
security:
  - openId:
      - trireg2-user