type: "object"
required: ["tagConfigurationName", "tagConfigurationValueType"]
properties:
  tagConfigurationName:
    type: "string"
    description: "The name of the tag configuration"
  tagConfigurationDescription:
    type: "string"
    description: "A description of the tag configuration"
  tagConfigurationValueType:
    $ref: "TagConfigurationValueType.yaml"