type: "object"
required: ["tagConfigurationId", "tagConfigurationName", "tagConfigurationValueType"]
properties:
  tagConfigurationId:
    type: "integer"
    format: "int64"
  tagConfigurationName:
    type: "string"
    description: "The name of the tag configuration"
  tagConfigurationDescription:
    type: "string"
    description: "A description of the tag configuration"
  tagConfigurationValueType:
    $ref: "TagConfigurationValueType.yaml"
