get:
  tags:
    - "TagConfiguration"
  operationId: "getTagConfigurations"
  description: "Gets all tag configurations that are applicable to the provided task"
  parameters:
    - name: "taskId"
      in: "query"
      description: "The id of the task to get applicable tag configurations for"
      required: true
      schema:
        type: "integer"
        format: "int64"
    - name: "includeHidden"
      in: "query"
      description: "Include tags that are normally hidden and automatically added when registering time on the task"
      required: false
      schema:
        type: "boolean"
  responses:
    "200":
      description: "List of valid tag configurations for the specified task"
      content:
        application/json:
          schema:
            $ref: "../schemas/admin/TagConfigurationResponse.yaml"
    "401":
      $ref: "../responses/UnauthorizedError.yaml"
    "404":
      description: "Unable to find tag configurations for the specified task (No task with specified taskId exists)"
post:
  tags:
    - "TagConfiguration"
  operationId: "createTagConfiguration"
  description: "Creates a new tag configuration"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schemas/admin/TagConfigurationCreateRequest.yaml"
  responses:
    "200":
      description: "The tag configuration was successfully created"
      content:
        text/plain:
          schema:
            type: "string"
    "400":
      description: "Request contains invalid data. The tag configuration was not created"
      content:
        text/plain:
          schema:
            type: "string"
    "401":
      $ref: "../responses/UnauthorizedError.yaml"
put:
  tags:
    - "TagConfigurations"
  operationId: "updateTagConfiguration"
  description: "Updates an existing tag configuration"
  parameters:
    - name: "tagConfigurationId"
      in: "query"
      description: "The id of the tag configuration to update"
      required: true
      schema:
        type: "integer"
        format: "int64"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schemas/admin/TagConfigurationUpdateRequest.yaml"
  responses:
    "200":
      description: "The tag configuration was successfully updated"
      content:
        text/plain:
          schema:
            type: "string"
    "400":
      description: "Request contains invalid data. The tag configuration was not updated"
      content:
        text/plain:
          schema:
            type: "string"
    "401":
      $ref: "../responses/UnauthorizedError.yaml"
    "404":
      description: "The specified task configuration was not found"
      content:
        text/plain:
          schema:
            type: "string"