name: Zip and publish Open API specification with gradle to Github maven repository
on:
  release:
    types: [ created ]

jobs:
  package-and-publish:
    name: Package and publish to Github packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Clean and build with gradle
        run: gradle clean build
      - name: Run publish with gradle
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gradle openapi:publish
